<a href="https://colab.research.google.com/github/MalathyParamasivam/dummyy/blob/main/Python%20DA%20Assignment%201%E2%80%94Numpy%20and%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Array Operations:**



In [4]:
import numpy as np
import pandas as pd

**1.Create a 1D NumPy Array:**

In [2]:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

**2. Inspection and Properties**

In [6]:
temperatures_w1.shape
temperatures_w1.dtype
temperatures_w1.size

7

**3.Array Operations**

3a.Convert the temperatures_w1 from Celsius to Fahrenheit using the formula:Fahrenheit = (Celsius * 9/5) + 32

In [7]:
temperatures_f=(temperatures_w1*9/5)+32
temperatures_f

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

3b.Find the maximum, minimum, and mean temperatures for the week.


In [10]:
temperatures_f.max()
temperatures_f.min()
temperatures_f.mean()

np.float64(74.37714285714286)

**4.Array Slicing and Indexing**

4a.Extract the temperatures for the first three days of the week


In [11]:
temperatures_f[0:3]

array([72.5 , 77.54, 69.44])

4b.Extract the temperatures for the weekend (last two days)

In [12]:
temperatures_f[-2:]

array([76.64, 71.42])

4c.Extract the temperatures for the middle three days of the week


In [13]:
temperatures_f[2:5]

array([69.44, 74.12, 78.98])

**5.Create a 2D Array**

In [14]:
temperatures=np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

**6.Inspect and Slice the 2D Array**

6a.Inspect and print the shape, data type, and total number of elements in the temperatures array.


In [15]:
temperatures.shape
temperatures.dtype
temperatures.size

14

6b.Extract the temperatures for each week and the weekends (last two days) for both weeks.


In [16]:
temperatures[:, -2:]

array([[24.8, 21.9],
       [22.8, 20.1]])

**1.Creating Pandas Series**

In [17]:
marks=pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
marks

,0
Rank1,95
Rank2,92
Rank3,89
Rank4,85
Rank5,80


**2.Indexing and Slicing**

2a.Use the integer index position to access the mark of the 1st rank student.

In [18]:
marks.iloc[0]

np.int64(95)

2b.Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.

In [19]:
marks.loc[["Rank1","Rank2","Rank3"]]

,0
Rank1,95
Rank2,92
Rank3,89


2c.Use the iloc accessor to retrieve the mark of the 3rd-ranked student

In [20]:
marks.iloc[2]

np.int64(89)

2d.Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.

In [21]:
marks[marks>90]

,0
Rank1,95
Rank2,92


**3.Manipulating Series**

3a.Modify the mark of the student with the 1st rank to 100.

In [22]:
marks.loc["Rank1"]=100
marks

,0
Rank1,100
Rank2,92
Rank3,89
Rank4,85
Rank5,80


3b.Remove the entry corresponding to the last rank from the Series.

In [23]:
marks=marks.drop("Rank5")
marks

,0
Rank1,100
Rank2,92
Rank3,89
Rank4,85


3c.Compute the CGPA by dividing each mark in the Series by 10.

In [24]:
cgpa=marks/10
cgpa

,0
Rank1,10.0
Rank2,9.2
Rank3,8.9
Rank4,8.5


**Pandas DataFrame:**

**1.Creating Pandas DataFrame:**

In [5]:
transactions=pd.DataFrame({"TransactionID":[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
                           "ProductCategory":['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
                           "Region":['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South',
'North'],"Amount":[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


**2. Data Exploration:**

2a.Display the transactions DataFrame and its basic information, including head, tail,
shape, column names, and data types.

In [6]:
transactions.head()
transactions.tail()
transactions.columns
transactions.dtypes
transactions.shape

(10, 4)

2b.Retrieve the last 3 columns of the DataFrame using iloc or loc.

In [7]:
transactions.iloc[:, 1:4]

,ProductCategory,Region,Amount
0,Electronics,North,200
1,Clothing,South,150
2,Electronics,North,300
3,Furniture,East,450
4,Clothing,West,200
5,Electronics,North,250
6,Furniture,East,300
7,Clothing,West,180
8,Furniture,South,350
9,Electronics,North,400


2c.Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

In [8]:
transactions[(transactions["Region"] == "North") & (transactions["Amount"] >200)]

,TransactionID,ProductCategory,Region,Amount
2,103,Electronics,North,300
5,106,Electronics,North,250
9,110,Electronics,North,400


2d.Find the value counts for the 'ProductCategory' column.

In [10]:
transactions["ProductCategory"].value_counts()

,count
ProductCategory,
Electronics,4
Clothing,3
Furniture,3


2e.Find the unique values in the 'Region' column.

In [11]:
transactions["Region"].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

2f.Group by 'Region' and find the mean amount for each region.

In [12]:
transactions.groupby("Region")["Amount"].mean()

,Amount
Region,
East,375.0
North,287.5
South,250.0
West,190.0


**3.Manipulating the DataFrame**

3a.Modify the 'Amount' for the transaction with TransactionID 102 to 165.

In [15]:
transactions.loc[transactions["TransactionID"] ==102, "Amount"] =165
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,165
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


3b.Add a new column 'Discount' by calculating 10% of the 'Amount'.

In [17]:
transactions["Discount"]=transactions["Amount"]*0.10
transactions

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
8,109,Furniture,South,350,35.0
9,110,Electronics,North,400,40.0


3c.Remove the row with TransactionID 109.

In [30]:
transactions

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0


3d.Delete the 'Discount' column from the DataFrame.

In [34]:
transactions = transactions.drop("Discount", axis=1)
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')